package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1



/**
 * ArticleDetailImages generated by hbm2java
 */
public class ArticleDetailImages  implements java.io.Serializable {


     private Integer idarticleDetailImages;
     private Article article;
     private DetailImages detailImages;

    public ArticleDetailImages() {
    }

    public ArticleDetailImages(Article article, DetailImages detailImages) {
       this.article = article;
       this.detailImages = detailImages;
    }
   
    public Integer getIdarticleDetailImages() {
        return this.idarticleDetailImages;
    }
    
    public void setIdarticleDetailImages(Integer idarticleDetailImages) {
        this.idarticleDetailImages = idarticleDetailImages;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public DetailImages getDetailImages() {
        return this.detailImages;
    }
    
    public void setDetailImages(DetailImages detailImages) {
        this.detailImages = detailImages;
    }




}


