package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1



/**
 * ArticleTags generated by hbm2java
 */
public class ArticleTags  implements java.io.Serializable {


     private Integer idarticleTags;
     private Article article;
     private Tags tags;

    public ArticleTags() {
    }

    public ArticleTags(Article article, Tags tags) {
       this.article = article;
       this.tags = tags;
    }
   
    public Integer getIdarticleTags() {
        return this.idarticleTags;
    }
    
    public void setIdarticleTags(Integer idarticleTags) {
        this.idarticleTags = idarticleTags;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Tags getTags() {
        return this.tags;
    }
    
    public void setTags(Tags tags) {
        this.tags = tags;
    }




}


