package com.javaweb.model;
// Generated Dec 22, 2016 4:28:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Integer idarticle;
     private String titleArticle;
     private String headline;
     private Date createdDate;
     private int creater;
     private Date modifiedDate;
     private String content;
     private String thumbnail;
     private Boolean public_;
     private String note;

    public Article() {
    }

	
    public Article(String titleArticle, String headline, Date createdDate, int creater, String content, String thumbnail) {
        this.titleArticle = titleArticle;
        this.headline = headline;
        this.createdDate = createdDate;
        this.creater = creater;
        this.content = content;
        this.thumbnail = thumbnail;
    }
    public Article(String titleArticle, String headline, Date createdDate, int creater, Date modifiedDate, String content, String thumbnail, Boolean public_, String note) {
       this.titleArticle = titleArticle;
       this.headline = headline;
       this.createdDate = createdDate;
       this.creater = creater;
       this.modifiedDate = modifiedDate;
       this.content = content;
       this.thumbnail = thumbnail;
       this.public_ = public_;
       this.note = note;
    }
   
    public Integer getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(Integer idarticle) {
        this.idarticle = idarticle;
    }
    public String getTitleArticle() {
        return this.titleArticle;
    }
    
    public void setTitleArticle(String titleArticle) {
        this.titleArticle = titleArticle;
    }
    public String getHeadline() {
        return this.headline;
    }
    
    public void setHeadline(String headline) {
        this.headline = headline;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public int getCreater() {
        return this.creater;
    }
    
    public void setCreater(int creater) {
        this.creater = creater;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getThumbnail() {
        return this.thumbnail;
    }
    
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }
    public Boolean getPublic_() {
        return this.public_;
    }
    
    public void setPublic_(Boolean public_) {
        this.public_ = public_;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


