package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer idcomment;
     private Article article;
     private String nameUser;
     private Date dateComment;
     private int commentReply;
     private String content;
     private String note;

    public Comment() {
    }

	
    public Comment(Article article, String nameUser, int commentReply, String content) {
        this.article = article;
        this.nameUser = nameUser;
        this.commentReply = commentReply;
        this.content = content;
    }
    public Comment(Article article, String nameUser, Date dateComment, int commentReply, String content, String note) {
       this.article = article;
       this.nameUser = nameUser;
       this.dateComment = dateComment;
       this.commentReply = commentReply;
       this.content = content;
       this.note = note;
    }
   
    public Integer getIdcomment() {
        return this.idcomment;
    }
    
    public void setIdcomment(Integer idcomment) {
        this.idcomment = idcomment;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public String getNameUser() {
        return this.nameUser;
    }
    
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser;
    }
    public Date getDateComment() {
        return this.dateComment;
    }
    
    public void setDateComment(Date dateComment) {
        this.dateComment = dateComment;
    }
    public int getCommentReply() {
        return this.commentReply;
    }
    
    public void setCommentReply(int commentReply) {
        this.commentReply = commentReply;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


