package com.javaweb.model;
// Generated Dec 4, 2016 9:52:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer idcomment;
     private String nameUser;
     private int idArticle;
     private Date dateComment;
     private int commentReply;
     private String content;
     private String ip;
     private String note;

    public Comment() {
    }

	
    public Comment(String nameUser, int idArticle, Date dateComment, int commentReply, String content, String ip) {
        this.nameUser = nameUser;
        this.idArticle = idArticle;
        this.dateComment = dateComment;
        this.commentReply = commentReply;
        this.content = content;
        this.ip = ip;
    }
    public Comment(String nameUser, int idArticle, Date dateComment, int commentReply, String content, String ip, String note) {
       this.nameUser = nameUser;
       this.idArticle = idArticle;
       this.dateComment = dateComment;
       this.commentReply = commentReply;
       this.content = content;
       this.ip = ip;
       this.note = note;
    }
   
    public Integer getIdcomment() {
        return this.idcomment;
    }
    
    public void setIdcomment(Integer idcomment) {
        this.idcomment = idcomment;
    }
    public String getNameUser() {
        return this.nameUser;
    }
    
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser;
    }
    public int getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(int idArticle) {
        this.idArticle = idArticle;
    }
    public Date getDateComment() {
        return this.dateComment;
    }
    
    public void setDateComment(Date dateComment) {
        this.dateComment = dateComment;
    }
    public int getCommentReply() {
        return this.commentReply;
    }
    
    public void setCommentReply(int commentReply) {
        this.commentReply = commentReply;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


