package com.javaweb.model;
// Generated Dec 2, 2016 1:44:12 PM by Hibernate Tools 4.3.1



/**
 * DetailImages generated by hbm2java
 */
public class DetailImages  implements java.io.Serializable {


     private Integer iddetailImages;
     private String imageName;

    public DetailImages() {
    }

    public DetailImages(String imageName) {
       this.imageName = imageName;
    }
   
    public Integer getIddetailImages() {
        return this.iddetailImages;
    }
    
    public void setIddetailImages(Integer iddetailImages) {
        this.iddetailImages = iddetailImages;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }




}


