package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DetailImages generated by hbm2java
 */
public class DetailImages  implements java.io.Serializable {


     private Integer iddetailImages;
     private String imageName;
     private Set<ArticleDetailImages> articleDetailImageses = new HashSet<ArticleDetailImages>(0);

    public DetailImages() {
    }

	
    public DetailImages(String imageName) {
        this.imageName = imageName;
    }
    public DetailImages(String imageName, Set<ArticleDetailImages> articleDetailImageses) {
       this.imageName = imageName;
       this.articleDetailImageses = articleDetailImageses;
    }
   
    public Integer getIddetailImages() {
        return this.iddetailImages;
    }
    
    public void setIddetailImages(Integer iddetailImages) {
        this.iddetailImages = iddetailImages;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public Set<ArticleDetailImages> getArticleDetailImageses() {
        return this.articleDetailImageses;
    }
    
    public void setArticleDetailImageses(Set<ArticleDetailImages> articleDetailImageses) {
        this.articleDetailImageses = articleDetailImageses;
    }




}


