package com.javaweb.model;
// Generated Dec 1, 2016 3:28:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DetailImages generated by hbm2java
 */
public class DetailImages  implements java.io.Serializable {


     private Integer iddetailImages;
     private String imageName;
     private Set<ProductDetailImages> productDetailImageses = new HashSet<ProductDetailImages>(0);

    public DetailImages() {
    }

	
    public DetailImages(String imageName) {
        this.imageName = imageName;
    }
    public DetailImages(String imageName, Set<ProductDetailImages> productDetailImageses) {
       this.imageName = imageName;
       this.productDetailImageses = productDetailImageses;
    }
   
    public Integer getIddetailImages() {
        return this.iddetailImages;
    }
    
    public void setIddetailImages(Integer iddetailImages) {
        this.iddetailImages = iddetailImages;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public Set<ProductDetailImages> getProductDetailImageses() {
        return this.productDetailImageses;
    }
    
    public void setProductDetailImageses(Set<ProductDetailImages> productDetailImageses) {
        this.productDetailImageses = productDetailImageses;
    }




}


