package com.javaweb.model;
// Generated Jan 1, 2017 11:24:49 AM by Hibernate Tools 4.3.1



/**
 * LikeDislike generated by hbm2java
 */
public class LikeDislike  implements java.io.Serializable {


     private Integer idlikeDislike;
     private int idArticle;
     private Boolean likeOrDislike;
     private String ip;
     private String mac;

    public LikeDislike() {
    }

	
    public LikeDislike(int idArticle, String ip, String mac) {
        this.idArticle = idArticle;
        this.ip = ip;
        this.mac = mac;
    }
    public LikeDislike(int idArticle, Boolean likeOrDislike, String ip, String mac) {
       this.idArticle = idArticle;
       this.likeOrDislike = likeOrDislike;
       this.ip = ip;
       this.mac = mac;
    }
   
    public Integer getIdlikeDislike() {
        return this.idlikeDislike;
    }
    
    public void setIdlikeDislike(Integer idlikeDislike) {
        this.idlikeDislike = idlikeDislike;
    }
    public int getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(int idArticle) {
        this.idArticle = idArticle;
    }
    public Boolean getLikeOrDislike() {
        return this.likeOrDislike;
    }
    
    public void setLikeOrDislike(Boolean likeOrDislike) {
        this.likeOrDislike = likeOrDislike;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }




}


