package com.javaweb.model;
// Generated Dec 1, 2016 3:28:02 PM by Hibernate Tools 4.3.1



/**
 * LikeDislike generated by hbm2java
 */
public class LikeDislike  implements java.io.Serializable {


     private Integer idlike;
     private Article article;
     private Boolean likeOrDislike;
     private String ip;
     private String mac;

    public LikeDislike() {
    }

	
    public LikeDislike(Article article, String ip) {
        this.article = article;
        this.ip = ip;
    }
    public LikeDislike(Article article, Boolean likeOrDislike, String ip, String mac) {
       this.article = article;
       this.likeOrDislike = likeOrDislike;
       this.ip = ip;
       this.mac = mac;
    }
   
    public Integer getIdlike() {
        return this.idlike;
    }
    
    public void setIdlike(Integer idlike) {
        this.idlike = idlike;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Boolean getLikeOrDislike() {
        return this.likeOrDislike;
    }
    
    public void setLikeOrDislike(Boolean likeOrDislike) {
        this.likeOrDislike = likeOrDislike;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }




}


