package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1



/**
 * LikeDislike generated by hbm2java
 */
public class LikeDislike  implements java.io.Serializable {


     private Integer idlike;
     private Article article;
     private Boolean likeOrDislike;

    public LikeDislike() {
    }

	
    public LikeDislike(Article article) {
        this.article = article;
    }
    public LikeDislike(Article article, Boolean likeOrDislike) {
       this.article = article;
       this.likeOrDislike = likeOrDislike;
    }
   
    public Integer getIdlike() {
        return this.idlike;
    }
    
    public void setIdlike(Integer idlike) {
        this.idlike = idlike;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Boolean getLikeOrDislike() {
        return this.likeOrDislike;
    }
    
    public void setLikeOrDislike(Boolean likeOrDislike) {
        this.likeOrDislike = likeOrDislike;
    }




}


