package com.javaweb.model;
// Generated Dec 1, 2016 3:28:02 PM by Hibernate Tools 4.3.1



/**
 * ProductTags generated by hbm2java
 */
public class ProductTags  implements java.io.Serializable {


     private Integer idproductTags;
     private Product product;
     private Tags tags;

    public ProductTags() {
    }

    public ProductTags(Product product, Tags tags) {
       this.product = product;
       this.tags = tags;
    }
   
    public Integer getIdproductTags() {
        return this.idproductTags;
    }
    
    public void setIdproductTags(Integer idproductTags) {
        this.idproductTags = idproductTags;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Tags getTags() {
        return this.tags;
    }
    
    public void setTags(Tags tags) {
        this.tags = tags;
    }




}


