package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1



/**
 * ProductSize generated by hbm2java
 */
public class ProductSize  implements java.io.Serializable {


     private Integer idproductSize;
     private Product product;
     private Size size;

    public ProductSize() {
    }

    public ProductSize(Product product, Size size) {
       this.product = product;
       this.size = size;
    }
   
    public Integer getIdproductSize() {
        return this.idproductSize;
    }
    
    public void setIdproductSize(Integer idproductSize) {
        this.idproductSize = idproductSize;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Size getSize() {
        return this.size;
    }
    
    public void setSize(Size size) {
        this.size = size;
    }




}


