package com.javaweb.model;
// Generated Dec 2, 2016 1:44:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idproduct;
     private String productNumber;
     private String productName;
     private double pricePerUnit;
     private double boughtPrice;
     private int productQuantity;
     private String unit;
     private String description;
     private int idproductCategory;
     private Date createdDate;
     private int creater;
     private Date dateModified;
     private String productImage;
     private int idPromotion;
     private String note;

    public Product() {
    }

	
    public Product(String productNumber, String productName, double pricePerUnit, double boughtPrice, int productQuantity, String unit, String describe, int idproductCategory, int creater, String productImage, int idPromotion) {
        this.productNumber = productNumber;
        this.productName = productName;
        this.pricePerUnit = pricePerUnit;
        this.boughtPrice = boughtPrice;
        this.productQuantity = productQuantity;
        this.unit = unit;
        this.description = describe;
        this.idproductCategory = idproductCategory;
        this.creater = creater;
        this.productImage = productImage;
        this.idPromotion = idPromotion;
    }
    public Product(String productNumber, String productName, double pricePerUnit, double boughtPrice, int productQuantity, String unit, String describe, int idproductCategory, Date createdDate, int creater, Date dateModified, String productImage, int idPromotion, String note) {
       this.productNumber = productNumber;
       this.productName = productName;
       this.pricePerUnit = pricePerUnit;
       this.boughtPrice = boughtPrice;
       this.productQuantity = productQuantity;
       this.unit = unit;
       this.description = describe;
       this.idproductCategory = idproductCategory;
       this.createdDate = createdDate;
       this.creater = creater;
       this.dateModified = dateModified;
       this.productImage = productImage;
       this.idPromotion = idPromotion;
       this.note = note;
    }
   
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }
    public String getProductNumber() {
        return this.productNumber;
    }
    
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public double getPricePerUnit() {
        return this.pricePerUnit;
    }
    
    public void setPricePerUnit(double pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
    }
    public double getBoughtPrice() {
        return this.boughtPrice;
    }
    
    public void setBoughtPrice(double boughtPrice) {
        this.boughtPrice = boughtPrice;
    }
    public int getProductQuantity() {
        return this.productQuantity;
    }
    
    public void setProductQuantity(int productQuantity) {
        this.productQuantity = productQuantity;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getIdproductCategory() {
        return this.idproductCategory;
    }
    
    public void setIdproductCategory(int idproductCategory) {
        this.idproductCategory = idproductCategory;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public int getCreater() {
        return this.creater;
    }
    
    public void setCreater(int creater) {
        this.creater = creater;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }
    public int getIdPromotion() {
        return this.idPromotion;
    }
    
    public void setIdPromotion(int idPromotion) {
        this.idPromotion = idPromotion;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


