package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategory generated by hbm2java
 */
public class ProductCategory  implements java.io.Serializable {


     private Integer idproductCategory;
     private String categoryName;
     private String note;
     private Set<Product> products = new HashSet<Product>(0);

    public ProductCategory() {
    }

	
    public ProductCategory(String categoryName) {
        this.categoryName = categoryName;
    }
    public ProductCategory(String categoryName, String note, Set<Product> products) {
       this.categoryName = categoryName;
       this.note = note;
       this.products = products;
    }
   
    public Integer getIdproductCategory() {
        return this.idproductCategory;
    }
    
    public void setIdproductCategory(Integer idproductCategory) {
        this.idproductCategory = idproductCategory;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


