package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idproduct;
     private ProductCategory productCategory;
     private User user;
     private String productName;
     private double salePrice;
     private double boughtPrice;
     private int productQuantity;
     private String unit;
     private Date createdDate;
     private Date dateModified;
     private String productImage;
     private String note;
     private Set<VendorInvoiceDetail> vendorInvoiceDetails = new HashSet<VendorInvoiceDetail>(0);
     private Set<ProductTags> productTagses = new HashSet<ProductTags>(0);
     private Set<ProductSize> productSizes = new HashSet<ProductSize>(0);
     private Set<ProductRating> productRatings = new HashSet<ProductRating>(0);
     private Set<ReceiptDetail> receiptDetails = new HashSet<ReceiptDetail>(0);

    public Product() {
    }

	
    public Product(ProductCategory productCategory, User user, String productName, double salePrice, double boughtPrice, int productQuantity, String unit) {
        this.productCategory = productCategory;
        this.user = user;
        this.productName = productName;
        this.salePrice = salePrice;
        this.boughtPrice = boughtPrice;
        this.productQuantity = productQuantity;
        this.unit = unit;
    }
    public Product(ProductCategory productCategory, User user, String productName, double salePrice, double boughtPrice, int productQuantity, String unit, Date createdDate, Date dateModified, String productImage, String note, Set<VendorInvoiceDetail> vendorInvoiceDetails, Set<ProductTags> productTagses, Set<ProductSize> productSizes, Set<ProductRating> productRatings, Set<ReceiptDetail> receiptDetails) {
       this.productCategory = productCategory;
       this.user = user;
       this.productName = productName;
       this.salePrice = salePrice;
       this.boughtPrice = boughtPrice;
       this.productQuantity = productQuantity;
       this.unit = unit;
       this.createdDate = createdDate;
       this.dateModified = dateModified;
       this.productImage = productImage;
       this.note = note;
       this.vendorInvoiceDetails = vendorInvoiceDetails;
       this.productTagses = productTagses;
       this.productSizes = productSizes;
       this.productRatings = productRatings;
       this.receiptDetails = receiptDetails;
    }
   
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }
    public ProductCategory getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(ProductCategory productCategory) {
        this.productCategory = productCategory;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public double getSalePrice() {
        return this.salePrice;
    }
    
    public void setSalePrice(double salePrice) {
        this.salePrice = salePrice;
    }
    public double getBoughtPrice() {
        return this.boughtPrice;
    }
    
    public void setBoughtPrice(double boughtPrice) {
        this.boughtPrice = boughtPrice;
    }
    public int getProductQuantity() {
        return this.productQuantity;
    }
    
    public void setProductQuantity(int productQuantity) {
        this.productQuantity = productQuantity;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<VendorInvoiceDetail> getVendorInvoiceDetails() {
        return this.vendorInvoiceDetails;
    }
    
    public void setVendorInvoiceDetails(Set<VendorInvoiceDetail> vendorInvoiceDetails) {
        this.vendorInvoiceDetails = vendorInvoiceDetails;
    }
    public Set<ProductTags> getProductTagses() {
        return this.productTagses;
    }
    
    public void setProductTagses(Set<ProductTags> productTagses) {
        this.productTagses = productTagses;
    }
    public Set<ProductSize> getProductSizes() {
        return this.productSizes;
    }
    
    public void setProductSizes(Set<ProductSize> productSizes) {
        this.productSizes = productSizes;
    }
    public Set<ProductRating> getProductRatings() {
        return this.productRatings;
    }
    
    public void setProductRatings(Set<ProductRating> productRatings) {
        this.productRatings = productRatings;
    }
    public Set<ReceiptDetail> getReceiptDetails() {
        return this.receiptDetails;
    }
    
    public void setReceiptDetails(Set<ReceiptDetail> receiptDetails) {
        this.receiptDetails = receiptDetails;
    }




}


