package com.javaweb.model;
// Generated Dec 1, 2016 3:28:02 PM by Hibernate Tools 4.3.1



/**
 * ProductDetailImages generated by hbm2java
 */
public class ProductDetailImages  implements java.io.Serializable {


     private Integer idproductDetailImages;
     private DetailImages detailImages;
     private int idProduct;

    public ProductDetailImages() {
    }

    public ProductDetailImages(DetailImages detailImages, int idProduct) {
       this.detailImages = detailImages;
       this.idProduct = idProduct;
    }
   
    public Integer getIdproductDetailImages() {
        return this.idproductDetailImages;
    }
    
    public void setIdproductDetailImages(Integer idproductDetailImages) {
        this.idproductDetailImages = idproductDetailImages;
    }
    public DetailImages getDetailImages() {
        return this.detailImages;
    }
    
    public void setDetailImages(DetailImages detailImages) {
        this.detailImages = detailImages;
    }
    public int getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(int idProduct) {
        this.idProduct = idProduct;
    }




}


