package com.javaweb.model;
// Generated Dec 1, 2016 3:28:02 PM by Hibernate Tools 4.3.1



/**
 * ProductRating generated by hbm2java
 */
public class ProductRating  implements java.io.Serializable {


     private Integer idproductRating;
     private Product product;
     private Rating rating;

    public ProductRating() {
    }

    public ProductRating(Product product, Rating rating) {
       this.product = product;
       this.rating = rating;
    }
   
    public Integer getIdproductRating() {
        return this.idproductRating;
    }
    
    public void setIdproductRating(Integer idproductRating) {
        this.idproductRating = idproductRating;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Rating getRating() {
        return this.rating;
    }
    
    public void setRating(Rating rating) {
        this.rating = rating;
    }




}


