package com.javaweb.model;
// Generated Dec 2, 2016 10:24:32 AM by Hibernate Tools 4.3.1



/**
 * ProductRating generated by hbm2java
 */
public class ProductRating  implements java.io.Serializable {


     private Integer idproductRating;
     private int idProduct;
     private int idRating;

    public ProductRating() {
    }

    public ProductRating(int idProduct, int idRating) {
       this.idProduct = idProduct;
       this.idRating = idRating;
    }
   
    public Integer getIdproductRating() {
        return this.idproductRating;
    }
    
    public void setIdproductRating(Integer idproductRating) {
        this.idproductRating = idproductRating;
    }
    public int getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(int idProduct) {
        this.idProduct = idProduct;
    }
    public int getIdRating() {
        return this.idRating;
    }
    
    public void setIdRating(int idRating) {
        this.idRating = idRating;
    }




}


