package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private Integer idrating;
     private int ratingPoint;
     private Set<ProductRating> productRatings = new HashSet<ProductRating>(0);

    public Rating() {
    }

	
    public Rating(int ratingPoint) {
        this.ratingPoint = ratingPoint;
    }
    public Rating(int ratingPoint, Set<ProductRating> productRatings) {
       this.ratingPoint = ratingPoint;
       this.productRatings = productRatings;
    }
   
    public Integer getIdrating() {
        return this.idrating;
    }
    
    public void setIdrating(Integer idrating) {
        this.idrating = idrating;
    }
    public int getRatingPoint() {
        return this.ratingPoint;
    }
    
    public void setRatingPoint(int ratingPoint) {
        this.ratingPoint = ratingPoint;
    }
    public Set<ProductRating> getProductRatings() {
        return this.productRatings;
    }
    
    public void setProductRatings(Set<ProductRating> productRatings) {
        this.productRatings = productRatings;
    }




}


