package com.javaweb.model;
// Generated Dec 9, 2016 6:54:57 PM by Hibernate Tools 4.3.1



/**
 * ReceiptDetail generated by hbm2java
 */
public class ReceiptDetail  implements java.io.Serializable {


     private Integer idreceiptDetail;
     private int idReceipt;
     private int idProduct;
     private int quantity;
     private double unitPrice;
     private String note;

    public ReceiptDetail() {
    }

	
    public ReceiptDetail(int idReceipt, int idProduct, int quantity, double unitPrice) {
        this.idReceipt = idReceipt;
        this.idProduct = idProduct;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }
    public ReceiptDetail(int idReceipt, int idProduct, int quantity, double unitPrice, String note) {
       this.idReceipt = idReceipt;
       this.idProduct = idProduct;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.note = note;
    }
   
    public Integer getIdreceiptDetail() {
        return this.idreceiptDetail;
    }
    
    public void setIdreceiptDetail(Integer idreceiptDetail) {
        this.idreceiptDetail = idreceiptDetail;
    }
    public int getIdReceipt() {
        return this.idReceipt;
    }
    
    public void setIdReceipt(int idReceipt) {
        this.idReceipt = idReceipt;
    }
    public int getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(int idProduct) {
        this.idProduct = idProduct;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


