package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Receipt generated by hbm2java
 */
public class Receipt  implements java.io.Serializable {


     private Integer idreceipt;
     private User userByCreater;
     private User userByBuyer;
     private String receiptNumber;
     private Date createdDate;
     private double totalPrice;
     private String note;
     private Set<ReceiptDetail> receiptDetails = new HashSet<ReceiptDetail>(0);

    public Receipt() {
    }

	
    public Receipt(User userByCreater, User userByBuyer, String receiptNumber, double totalPrice) {
        this.userByCreater = userByCreater;
        this.userByBuyer = userByBuyer;
        this.receiptNumber = receiptNumber;
        this.totalPrice = totalPrice;
    }
    public Receipt(User userByCreater, User userByBuyer, String receiptNumber, Date createdDate, double totalPrice, String note, Set<ReceiptDetail> receiptDetails) {
       this.userByCreater = userByCreater;
       this.userByBuyer = userByBuyer;
       this.receiptNumber = receiptNumber;
       this.createdDate = createdDate;
       this.totalPrice = totalPrice;
       this.note = note;
       this.receiptDetails = receiptDetails;
    }
   
    public Integer getIdreceipt() {
        return this.idreceipt;
    }
    
    public void setIdreceipt(Integer idreceipt) {
        this.idreceipt = idreceipt;
    }
    public User getUserByCreater() {
        return this.userByCreater;
    }
    
    public void setUserByCreater(User userByCreater) {
        this.userByCreater = userByCreater;
    }
    public User getUserByBuyer() {
        return this.userByBuyer;
    }
    
    public void setUserByBuyer(User userByBuyer) {
        this.userByBuyer = userByBuyer;
    }
    public String getReceiptNumber() {
        return this.receiptNumber;
    }
    
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<ReceiptDetail> getReceiptDetails() {
        return this.receiptDetails;
    }
    
    public void setReceiptDetails(Set<ReceiptDetail> receiptDetails) {
        this.receiptDetails = receiptDetails;
    }




}


