package com.javaweb.model;
// Generated Dec 14, 2016 10:55:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Receipt generated by hbm2java
 */
public class Receipt  implements java.io.Serializable {


     private Integer idreceipt;
     private String receiptNumber;
     private String email;
     private String address;
     private String phoneNumber;
     private int creater;
     private String buyer;
     private double totalPrice;
     private Date createdDate;
     private String status;
     private String note;

    public Receipt() {
    }

	
    public Receipt(String receiptNumber, String email, String address, String phoneNumber, int creater, String buyer, double totalPrice, Date createdDate, String status) {
        this.receiptNumber = receiptNumber;
        this.email = email;
        this.address = address;
        this.phoneNumber = phoneNumber;
        this.creater = creater;
        this.buyer = buyer;
        this.totalPrice = totalPrice;
        this.createdDate = createdDate;
        this.status = status;
    }
    public Receipt(String receiptNumber, String email, String address, String phoneNumber, int creater, String buyer, double totalPrice, Date createdDate, String status, String note) {
       this.receiptNumber = receiptNumber;
       this.email = email;
       this.address = address;
       this.phoneNumber = phoneNumber;
       this.creater = creater;
       this.buyer = buyer;
       this.totalPrice = totalPrice;
       this.createdDate = createdDate;
       this.status = status;
       this.note = note;
    }
   
    public Integer getIdreceipt() {
        return this.idreceipt;
    }
    
    public void setIdreceipt(Integer idreceipt) {
        this.idreceipt = idreceipt;
    }
    public String getReceiptNumber() {
        return this.receiptNumber;
    }
    
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public int getCreater() {
        return this.creater;
    }
    
    public void setCreater(int creater) {
        this.creater = creater;
    }
    public String getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(String buyer) {
        this.buyer = buyer;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


