package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1



/**
 * ReceiptDetail generated by hbm2java
 */
public class ReceiptDetail  implements java.io.Serializable {


     private Integer idreceiptDetail;
     private Product product;
     private Receipt receipt;
     private int quantity;
     private double unitPrice;
     private String note;

    public ReceiptDetail() {
    }

	
    public ReceiptDetail(Product product, Receipt receipt, int quantity, double unitPrice) {
        this.product = product;
        this.receipt = receipt;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }
    public ReceiptDetail(Product product, Receipt receipt, int quantity, double unitPrice, String note) {
       this.product = product;
       this.receipt = receipt;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.note = note;
    }
   
    public Integer getIdreceiptDetail() {
        return this.idreceiptDetail;
    }
    
    public void setIdreceiptDetail(Integer idreceiptDetail) {
        this.idreceiptDetail = idreceiptDetail;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


