package com.javaweb.model;
// Generated Dec 22, 2016 4:28:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Receipt generated by hbm2java
 */
public class Receipt  implements java.io.Serializable {


     private Integer idreceipt;
     private String receiptNumber;
     private Date createdDate;
     private int creater;
     private int buyer;
     private double totalPrice;
     private String note;

    public Receipt() {
    }

	
    public Receipt(String receiptNumber, Date createdDate, int creater, int buyer, double totalPrice) {
        this.receiptNumber = receiptNumber;
        this.createdDate = createdDate;
        this.creater = creater;
        this.buyer = buyer;
        this.totalPrice = totalPrice;
    }
    public Receipt(String receiptNumber, Date createdDate, int creater, int buyer, double totalPrice, String note) {
       this.receiptNumber = receiptNumber;
       this.createdDate = createdDate;
       this.creater = creater;
       this.buyer = buyer;
       this.totalPrice = totalPrice;
       this.note = note;
    }
   
    public Integer getIdreceipt() {
        return this.idreceipt;
    }
    
    public void setIdreceipt(Integer idreceipt) {
        this.idreceipt = idreceipt;
    }
    public String getReceiptNumber() {
        return this.receiptNumber;
    }
    
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public int getCreater() {
        return this.creater;
    }
    
    public void setCreater(int creater) {
        this.creater = creater;
    }
    public int getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(int buyer) {
        this.buyer = buyer;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


