package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RoleUser generated by hbm2java
 */
public class RoleUser  implements java.io.Serializable {


     private Integer idroleUser;
     private String roleName;
     private String note;
     private Set<User> users = new HashSet<User>(0);

    public RoleUser() {
    }

	
    public RoleUser(String roleName) {
        this.roleName = roleName;
    }
    public RoleUser(String roleName, String note, Set<User> users) {
       this.roleName = roleName;
       this.note = note;
       this.users = users;
    }
   
    public Integer getIdroleUser() {
        return this.idroleUser;
    }
    
    public void setIdroleUser(Integer idroleUser) {
        this.idroleUser = idroleUser;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


