package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Size generated by hbm2java
 */
public class Size  implements java.io.Serializable {


     private Integer idsize;
     private String sizeSymbol;
     private Set<ProductSize> productSizes = new HashSet<ProductSize>(0);

    public Size() {
    }

	
    public Size(String sizeSymbol) {
        this.sizeSymbol = sizeSymbol;
    }
    public Size(String sizeSymbol, Set<ProductSize> productSizes) {
       this.sizeSymbol = sizeSymbol;
       this.productSizes = productSizes;
    }
   
    public Integer getIdsize() {
        return this.idsize;
    }
    
    public void setIdsize(Integer idsize) {
        this.idsize = idsize;
    }
    public String getSizeSymbol() {
        return this.sizeSymbol;
    }
    
    public void setSizeSymbol(String sizeSymbol) {
        this.sizeSymbol = sizeSymbol;
    }
    public Set<ProductSize> getProductSizes() {
        return this.productSizes;
    }
    
    public void setProductSizes(Set<ProductSize> productSizes) {
        this.productSizes = productSizes;
    }




}


