package com.javaweb.model;
// Generated Dec 9, 2016 6:54:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String username;
     private String password;
     private int idroleUser;
     private String fullname;
     private boolean gender;
     private String userPhone;
     private String address;
     private String email;
     private Date birthday;
     private String image;
     private Boolean status;
     private String note;

    public User() {
    }

	
    public User(String username, String password, int idroleUser, String fullname, boolean gender, String email, Date birthday) {
        this.username = username;
        this.password = password;
        this.idroleUser = idroleUser;
        this.fullname = fullname;
        this.gender = gender;
        this.email = email;
        this.birthday = birthday;
    }
    public User(String username, String password, int idroleUser, String fullname, boolean gender, String userPhone, String address, String email, Date birthday, String image, Boolean status, String note) {
       this.username = username;
       this.password = password;
       this.idroleUser = idroleUser;
       this.fullname = fullname;
       this.gender = gender;
       this.userPhone = userPhone;
       this.address = address;
       this.email = email;
       this.birthday = birthday;
       this.image = image;
       this.status = status;
       this.note = note;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getIdroleUser() {
        return this.idroleUser;
    }
    
    public void setIdroleUser(int idroleUser) {
        this.idroleUser = idroleUser;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


