package com.javaweb.model;
// Generated Dec 1, 2016 3:28:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private RoleUser roleUser;
     private String username;
     private String password;
     private String fullname;
     private boolean gender;
     private String userPhone;
     private String address;
     private String email;
     private Date birthday;
     private String image;
     private Boolean status;
     private String note;
     private Set<VendorInvoice> vendorInvoices = new HashSet<VendorInvoice>(0);
     private Set<Product> products = new HashSet<Product>(0);
     private Set<Receipt> receiptsForCreater = new HashSet<Receipt>(0);
     private Set<Article> articles = new HashSet<Article>(0);
     private Set<Receipt> receiptsForBuyer = new HashSet<Receipt>(0);

    public User() {
    }

	
    public User(RoleUser roleUser, String username, String password, String fullname, boolean gender, String email, Date birthday) {
        this.roleUser = roleUser;
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.gender = gender;
        this.email = email;
        this.birthday = birthday;
    }
    public User(RoleUser roleUser, String username, String password, String fullname, boolean gender, String userPhone, String address, String email, Date birthday, String image, Boolean status, String note, Set<VendorInvoice> vendorInvoices, Set<Product> products, Set<Receipt> receiptsForCreater, Set<Article> articles, Set<Receipt> receiptsForBuyer) {
       this.roleUser = roleUser;
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.gender = gender;
       this.userPhone = userPhone;
       this.address = address;
       this.email = email;
       this.birthday = birthday;
       this.image = image;
       this.status = status;
       this.note = note;
       this.vendorInvoices = vendorInvoices;
       this.products = products;
       this.receiptsForCreater = receiptsForCreater;
       this.articles = articles;
       this.receiptsForBuyer = receiptsForBuyer;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public RoleUser getRoleUser() {
        return this.roleUser;
    }
    
    public void setRoleUser(RoleUser roleUser) {
        this.roleUser = roleUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public boolean getGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<VendorInvoice> getVendorInvoices() {
        return this.vendorInvoices;
    }
    
    public void setVendorInvoices(Set<VendorInvoice> vendorInvoices) {
        this.vendorInvoices = vendorInvoices;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }
    public Set<Receipt> getReceiptsForCreater() {
        return this.receiptsForCreater;
    }
    
    public void setReceiptsForCreater(Set<Receipt> receiptsForCreater) {
        this.receiptsForCreater = receiptsForCreater;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }
    public Set<Receipt> getReceiptsForBuyer() {
        return this.receiptsForBuyer;
    }
    
    public void setReceiptsForBuyer(Set<Receipt> receiptsForBuyer) {
        this.receiptsForBuyer = receiptsForBuyer;
    }




}


