package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendor generated by hbm2java
 */
public class Vendor  implements java.io.Serializable {


     private Integer idVendor;
     private String vendorName;
     private String vendorAddress;
     private String vendorPhone;
     private String note;
     private Set<VendorInvoice> vendorInvoices = new HashSet<VendorInvoice>(0);

    public Vendor() {
    }

	
    public Vendor(String vendorName, String vendorAddress) {
        this.vendorName = vendorName;
        this.vendorAddress = vendorAddress;
    }
    public Vendor(String vendorName, String vendorAddress, String vendorPhone, String note, Set<VendorInvoice> vendorInvoices) {
       this.vendorName = vendorName;
       this.vendorAddress = vendorAddress;
       this.vendorPhone = vendorPhone;
       this.note = note;
       this.vendorInvoices = vendorInvoices;
    }
   
    public Integer getIdVendor() {
        return this.idVendor;
    }
    
    public void setIdVendor(Integer idVendor) {
        this.idVendor = idVendor;
    }
    public String getVendorName() {
        return this.vendorName;
    }
    
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }
    public String getVendorAddress() {
        return this.vendorAddress;
    }
    
    public void setVendorAddress(String vendorAddress) {
        this.vendorAddress = vendorAddress;
    }
    public String getVendorPhone() {
        return this.vendorPhone;
    }
    
    public void setVendorPhone(String vendorPhone) {
        this.vendorPhone = vendorPhone;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<VendorInvoice> getVendorInvoices() {
        return this.vendorInvoices;
    }
    
    public void setVendorInvoices(Set<VendorInvoice> vendorInvoices) {
        this.vendorInvoices = vendorInvoices;
    }




}


