package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1



/**
 * VendorInvoiceDetail generated by hbm2java
 */
public class VendorInvoiceDetail  implements java.io.Serializable {


     private Integer idvendorInvoiceDetail;
     private Product product;
     private VendorInvoice vendorInvoice;
     private int quanity;
     private double unitPrice;
     private String note;

    public VendorInvoiceDetail() {
    }

	
    public VendorInvoiceDetail(Product product, VendorInvoice vendorInvoice, int quanity, double unitPrice) {
        this.product = product;
        this.vendorInvoice = vendorInvoice;
        this.quanity = quanity;
        this.unitPrice = unitPrice;
    }
    public VendorInvoiceDetail(Product product, VendorInvoice vendorInvoice, int quanity, double unitPrice, String note) {
       this.product = product;
       this.vendorInvoice = vendorInvoice;
       this.quanity = quanity;
       this.unitPrice = unitPrice;
       this.note = note;
    }
   
    public Integer getIdvendorInvoiceDetail() {
        return this.idvendorInvoiceDetail;
    }
    
    public void setIdvendorInvoiceDetail(Integer idvendorInvoiceDetail) {
        this.idvendorInvoiceDetail = idvendorInvoiceDetail;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public VendorInvoice getVendorInvoice() {
        return this.vendorInvoice;
    }
    
    public void setVendorInvoice(VendorInvoice vendorInvoice) {
        this.vendorInvoice = vendorInvoice;
    }
    public int getQuanity() {
        return this.quanity;
    }
    
    public void setQuanity(int quanity) {
        this.quanity = quanity;
    }
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


