package com.javaweb.model;
// Generated Nov 19, 2016 12:01:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VendorInvoice generated by hbm2java
 */
public class VendorInvoice  implements java.io.Serializable {


     private Integer idvendorInvoice;
     private User user;
     private Vendor vendor;
     private String vendorInvoiceNumber;
     private double totalPrice;
     private Date createdDate;
     private String note;
     private Set<VendorInvoiceDetail> vendorInvoiceDetails = new HashSet<VendorInvoiceDetail>(0);

    public VendorInvoice() {
    }

	
    public VendorInvoice(User user, Vendor vendor, String vendorInvoiceNumber, double totalPrice) {
        this.user = user;
        this.vendor = vendor;
        this.vendorInvoiceNumber = vendorInvoiceNumber;
        this.totalPrice = totalPrice;
    }
    public VendorInvoice(User user, Vendor vendor, String vendorInvoiceNumber, double totalPrice, Date createdDate, String note, Set<VendorInvoiceDetail> vendorInvoiceDetails) {
       this.user = user;
       this.vendor = vendor;
       this.vendorInvoiceNumber = vendorInvoiceNumber;
       this.totalPrice = totalPrice;
       this.createdDate = createdDate;
       this.note = note;
       this.vendorInvoiceDetails = vendorInvoiceDetails;
    }
   
    public Integer getIdvendorInvoice() {
        return this.idvendorInvoice;
    }
    
    public void setIdvendorInvoice(Integer idvendorInvoice) {
        this.idvendorInvoice = idvendorInvoice;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }
    public String getVendorInvoiceNumber() {
        return this.vendorInvoiceNumber;
    }
    
    public void setVendorInvoiceNumber(String vendorInvoiceNumber) {
        this.vendorInvoiceNumber = vendorInvoiceNumber;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<VendorInvoiceDetail> getVendorInvoiceDetails() {
        return this.vendorInvoiceDetails;
    }
    
    public void setVendorInvoiceDetails(Set<VendorInvoiceDetail> vendorInvoiceDetails) {
        this.vendorInvoiceDetails = vendorInvoiceDetails;
    }




}


